services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=My21252006AA!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "My21252006AA!", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  travel-agency-pl:
    build:
      context: .
      dockerfile: Travel_agency.PL/Dockerfile
    container_name: travel-agency-pl
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql-server;Database=TravelAgencyDB;User=sa;Password=My21252006AA!;TrustServerCertificate=True
    depends_on:
      mssql-server:
        condition: service_healthy
    networks:
      - app-network