version: "3.9"

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

  travel-agency-pl:
    build:
      context: .
      dockerfile: Travel_agency.PL/Dockerfile
    container_name: travel-agency-pl
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    networks:
      - app-network

  travel-agency-frontend:
    build:
      context: ./Travel_agency_frontend
      dockerfile: Dockerfile
    container_name: travel-agency-frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - travel-agency-pl

networks:
  app-network:
    driver: bridge

volumes:
  mssql_data: